FROM infotrainingdev/gcc14-clang18-cmake330-vcpkg:latest
#FROM infotrainingdev/gcc14-cmake329-vcpkg:latest
#FROM infotrainingdev/gcc13-clang17-cmake328-vcpkg:latest
WORKDIR /root

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

